authors = ["ScottPJones <scottjones@alum.mit.edu>"]
desc = "Entities from LaTeX data tables"
keywords = ["Entities", "LaTeX"]
license = "MIT"
name = "LaTeX_Entities"
uuid = "9927f19a-46ce-5bdd-a20a-f46a78b61e3d"
version = "0.2.6"

[deps]
Pkg  = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

StrTables = "9700d1a9-a7c8-5760-9816-a99fda30bb8f"

LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
